replicas: 1

appname: helloworld

imagePullSecrets:
    name: imagepull-docker

image: 
  repository: ramakrishna8254/week:v3
  tag: "v3"
  imagePullPolicy: Always

service:
  type: ClusterIP
  port: 8080

selector:
    matchLabels:
      app: hello-world

---


