apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appname}}
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: {{.Values.appname}}
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      imagePullSecrets:
      - name: imagepull-docker
      containers:
      - name: hello-world
        image: ramakrishna8254/week:v3
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
