apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appname}}
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: {{.Values.appname}}
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
      - name: hello-world
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{.Values.service.port}}
