apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appname}}
spec:
  ports:
  - port: {{.Values.service.port}}
    targetPort: http
  selector:
    app: {{.Values.appname}}
  type: {{ .Values.service.type }}